package autoclicker;

import cpw.mods.fml.common.ModMetadata;

public class AutoClickerModInfoCore {
	public static void registerInfo(ModMetadata meta) {
		meta.modId = AutoClickerMod.MOD_ID;
		meta.name = AutoClickerMod.MOD_NAME;
		meta.description = "This mod adds the ability to automatically attack entities if you can attack it.";
		meta.version = AutoClickerMod.MOD_VERSION;
		meta.url = "https://github.com/Zeroron-256/autoLeftClicker";
		meta.authorList.add("Zeroron");
		meta.autogenerated = false;
	}
}
