package autoclicker;

import cpw.mods.fml.common.ModMetadata;

public class AutoClickerModInfoCore {
  public static void registerInfo(ModMetadata meta) {
    meta.modId = "AutoLeftClicker";
    meta.name = "Auto Left Clicker";
    meta.description = "This mod adds the ability to automatically attack entities if you can attack it.";
    meta.version = "1.1.0";
    meta.url = "https://github.com/Zeroron-255/autoLeftClicker";
    meta.authorList.add("Zeroron");
    meta.autogenerated = false;
  }
}
