package autoclicker;

import cpw.mods.fml.common.ModMetadata;

public class AutoClickerModInfoCore {
  public static void registerInfo(ModMetadata meta) {
    meta.modId = "AutoClicker";
    meta.name = "Auto Clicker";
    meta.description = "This mod adds the some abilities to do automatically. ";
    meta.version = "1.1.0";
    meta.url = "https://github.com/Zeroron-255/AutoClicker";
    meta.authorList.add("Zeroron");
    meta.autogenerated = false;
  }
}
